<?php
/**
 * Pagination Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<nav>
    <ul class="pagination">
        <?php if ((int)$pagination_data->first_page_number == (int)$pagination_data->current_page_number) : ?>
            <li>&laquo; &laquo;</li>
        <?php else : ?>
            <li><a href="<?= $pagination_data->first_page_link; ?>">&laquo; &laquo;</a></li>
        <?php endif; ?>

        <?php if ((int)$pagination_data->previous_page_number == (int)$pagination_data->current_page_number) : ?>
            <li>&laquo;</li>
        <?php else : ?>
            <li><a href="<?= $pagination_data->previous_page_link; ?>">&laquo;</a></li>
        <?php endif; ?>

        <?php
        for ($i = $pagination_data->start_links_page_number;
             $i < $pagination_data->stop_links_page_number + 1;
             $i ++) {
                if ((int)$i == (int)$pagination_data->current_page_number) : ?>
                    <li class="current">
                <?php else : ?>
                    <li>
                <?php endif; ?>
            <a href="<?= $pagination_data->page_links_array[$i]; ?>"><?= $i; ?></a></li>
        <?php } ?>

        <?php if ((int)$pagination_data->next_page_number == (int)$pagination_data->current_page_number) : ?>
            <li>&raquo;</li>
        <?php else : ?>
            <li><a href="<?= $pagination_data->next_page_link; ?>">&raquo;</a></li>
        <?php endif; ?>

        <?php if ((int)$pagination_data->last_page_number == (int)$pagination_data->current_page_number) : ?>
            <li>&raquo; &raquo;</li>
        <?php else : ?>
            <li><a href="<?= $pagination_data->last_page_link; ?>">&raquo; &raquo;</a></li>
        <?php endif; ?>
    </ul>
</nav>
