<?php
/**
 * Sample Theme for Pagination
 *
 * @package    Molajo Pagination
 * @link       https://github.com/Molajo/Pagination
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Pagination Example</title>
    <link rel="stylesheet" href="/Theme/css/normalize.css"/>
    <link rel="stylesheet" href="/Theme/css/custom.css"/>
</head>
<body>
<div class="page-wrap">
    <?php include $view_base . 'Header.phtml'; ?>
    <?php include $view_base . 'List.phtml'; ?>
    <?php include $view_base . 'Pagination.phtml'; ?>
</div>
<?php include $view_base . 'Footer.phtml'; ?>
</body>
</html>
