<?php
/**
 * Sample Theme for Pagination
 *
 * @package    Molajo Pagination
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Molajo Pagination Example</title>
    <link rel="stylesheet" href="/Theme/css/normalize.css"/>
    <link rel="stylesheet" href="/Theme/css/custom.css"/>
</head>
<body>
<div class="old-school">
    <div class="page-wrap">
        <?php include $runtime_data->include->view_base_folder . '/Header.phtml'; ?>
        <?php include $runtime_data->include->view_base_folder . '/List.phtml'; ?>
        <?php include $runtime_data->include->view_base_folder . '/Pagination.phtml'; ?>
    </div>
    <?php include $runtime_data->include->view_base_folder . '/Footer.phtml'; ?>
</div>
</body>
</html>
